version: "3.7"

services:
  mongodb:
    image: mongo:6.0.6
    platform: linux/amd64
    container_name: 'mongo'
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  rabbitmq:
    image: rabbitmq:3.11.17-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    command: >
      bash -c "
        rabbitmq-plugins enable --offline rabbitmq_amqp1_0 &&
        rabbitmq-server
      "
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  order-service:
    image: dejmartins/order-service:latest
    platform: linux/amd64
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ORDER_QUEUE_URI=amqp://username:password@rabbitmq:5672
      - ORDER_QUEUE_HOSTNAME=rabbitmq
      - ORDER_QUEUE_USERNAME=username
      - ORDER_QUEUE_PASSWORD=password
      - ORDER_QUEUE_NAME=orders
      - ORDER_DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@mongo-vcore-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      # - ORDER_DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@cluster0.aeu72cc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - ORDER_DB_NAME=orderdb
      - ORDER_DB_COLLECTION_NAME=orders
      - ORDER_QUEUE_PORT=5672
      - ORDER_QUEUE_TRANSPORT=tcp
    networks:
      - backend_services

  makeline-service:
    image: dejmartins/makeline-service:latest
    container_name: 'makeline-service'
    restart: always
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://makeline-service:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ORDER_QUEUE_URI=amqp://username:password@rabbitmq:5672
      - ORDER_QUEUE_HOSTNAME=rabbitmq
      - ORDER_QUEUE_USERNAME=username
      - ORDER_QUEUE_PASSWORD=password
      - ORDER_QUEUE_NAME=orders
      - ORDER_DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@mongo-vcore-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      # - ORDER_DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@cluster0.aeu72cc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - ORDER_DB_NAME=orderdb
      - ORDER_DB_COLLECTION_NAME=orders
      - ORDER_QUEUE_PORT=5672
      - ORDER_QUEUE_TRANSPORT=tcp
    networks:
      - backend_services
    depends_on:
      mongodb:
        condition: service_healthy

  product-service:
    image: dejmartins/product-service:latest
    container_name: 'product-service'
    restart: always
    ports:
      - 3002:3002
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://product-service:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      # - DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@cluster0.aeu72cc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PRODUCT_DB_URI=mongodb+srv://username:E805tKmaZYEo0XZe@mongo-vcore-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge
