version: "3.7"
services:
  mongodb:
    image: mongo:6.0.6
    container_name: 'mongo'
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  order-service:
    image: ramymohamed/order-service-l8:latest
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://your-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yourkey
      - SERVICE_BUS_QUEUE_NAME=orders
      - SERVICE_BUS_RECONNECT_LIMIT=3
    networks:
      - backend_services

  makeline-service:
    image: ramymohamed/makeline-service-l8:latest
    container_name: 'makeline-service'
    restart: always
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://makeline-service:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://your-servicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yourkey
      - SERVICE_BUS_QUEUE_NAME=orders
      - ORDER_DB_URI=mongodb://mongodb:27017
      - ORDER_DB_NAME=orderdb
      - ORDER_DB_COLLECTION_NAME=orders
    networks:
      - backend_services
    depends_on:
      mongodb:
        condition: service_healthy

  product-service:
    image: ramymohamed/product-service-l8:latest
    container_name: 'product-service'
    restart: always
    ports:
      - 3002:3002
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://product-service:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  virtual-customer:
    image: ramymohamed/virtual-customer-l8:latest
    container_name: 'virtual-customer'
    restart: always
    environment:
      - ORDER_SERVICE_URL=http://order-service:3000/
      - ORDERS_PER_HOUR=3600
    networks:
      - backend_services
    depends_on:
      order-service:
        condition: service_healthy

  # ai-service:
  #   build: ../ai-service
  #   container_name: 'ai-service'
  #   restart: always
  #   ports:
  #     - 5001:5001
  #   healthcheck:
  #     test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://ai-service:5001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   environment:
  #     - USE_AZURE_OPENAI=True # set to False if you are not using Azure OpenAI
  #     - AZURE_OPENAI_DEPLOYMENT_NAME=
  #     - AZURE_OPENAI_ENDPOINT=
  #     - OPENAI_API_KEY=
  #     - OPENAI_ORG_ID=
  #   networks:
  #     - backend_services

networks:
  backend_services:
    driver: bridge
